version: '2'
services:
    draft99sample-app:
        image: draft99sample
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://draft99sample-mysql:3306/draft99sample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    draft99sample-mysql:
        extends:
            file: mysql.yml
            service: draft99sample-mysql
